providers = ["python"]

[phases.setup]
nixPkgs = ["python39", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p staticfiles"]

[start]
cmd = "python manage.py collectstatic --noinput --clear && python manage.py migrate && exec gunicorn core.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --log-level info"
